# Generated by Django 5.0.2 on 2024-02-19 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_listings', '0002_alter_stocklisting_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklisting',
            options={'ordering': ['title'], 'verbose_name': 'listing', 'verbose_name_plural': 'listings'},
        ),
        migrations.AddField(
            model_name='stocklisting',
            name='phone',
            field=models.CharField(default=7495381344, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocklisting',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='stocklisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='stocklisting',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stocklisting',
            name='user',
            field=models.ForeignKey(default=911, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
    ]
